# Generated by Django 6.0.6 on 2026-06-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('row', 'seat', 'flight')},
        ),
    ]
