# Generated by Django 6.0.6 on 2026-06-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ('departure_time',)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created_at',)},
        ),
    ]
