# Generated by Django 6.0.6 on 2026-07-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='airplanetype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='crew',
            options={'ordering': ('last_name',)},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('source',)},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('row', 'seat', 'flight')},
        ),
    ]
